configfile: "config/config.yaml"

rule all:
    input:
        "results/qc/multiqc_report.html",
        "results/plots/umap_rna.png",
        "results/plots/umap_atac.png",
        "results/plots/umap_wnn.png",
        "results/plots/umap_multivi.png",
        "results/plots/cellrank_trajectory.png",
        "results/plots/umap_markers.png",
        "results/plots/trajectory_pseudotime.png",
        "results/integrated_pbmc.zarr"

# Include modular rules
include: "rules/qc.smk"
include: "rules/analysis.smk"
