data:
  rna_matrix: "data/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5"
  atac_fragments: "data/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz"

params:
  min_genes: 200
  min_cells: 3
  pct_mito: 20
